import { parseSVG, makeAbsolute } from 'svg-path-parser';

function extractPaths(svgString) {
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgString, 'image/svg+xml');
  const paths = [];
  doc.querySelectorAll('path').forEach((el) => {
    const d = el.getAttribute('d');
    if (d) paths.push(d);
  });
  return paths;
}

function pathToPoints(d) {
  const commands = makeAbsolute(parseSVG(d));
  const points = [];
  for (const cmd of commands) {
    switch (cmd.code) {
      case 'M': case 'L':
        points.push({ type: cmd.code, x: cmd.x, y: cmd.y });
        break;
      case 'C':
        points.push({ type: 'L', x: cmd.x, y: cmd.y });
        break;
      case 'Q':
        points.push({ type: 'L', x: cmd.x, y: cmd.y });
        break;
      case 'Z':
        if (points.length > 0) {
          points.push({ type: 'Z', x: points[0].x, y: points[0].y });
        }
        break;
      default:
        if (cmd.x !== undefined && cmd.y !== undefined) {
          points.push({ type: 'L', x: cmd.x, y: cmd.y });
        }
    }
  }
  return points;
}

export function compileSVGToGCode(svgString, settings) {
  const {
    maxFeedrate = 1000,
    servoPenDown = 30,
    servoPenUp = 75,
  } = settings;

  const paths = extractPaths(svgString);
  const lines = [];

  lines.push('; Generated by Platform Control');
  lines.push('G21 ; mm units');
  lines.push('G90 ; absolute positioning');
  lines.push(`F${maxFeedrate}`);
  lines.push(`M280 P0 S${servoPenUp} ; pen up`);

  for (const d of paths) {
    const points = pathToPoints(d);
    if (points.length === 0) continue;

    let penDown = false;

    for (let i = 0; i < points.length; i++) {
      const pt = points[i];
      const x = pt.x.toFixed(3);
      const y = pt.y.toFixed(3);

      if (i === 0 || pt.type === 'M') {
        if (penDown) {
          lines.push(`M280 P0 S${servoPenUp} ; pen up`);
          penDown = false;
        }
        lines.push(`G0 X${x} Y${y}`);
      } else if (pt.type === 'Z') {
        lines.push(`G1 X${x} Y${y} F${maxFeedrate}`);
        lines.push(`M280 P0 S${servoPenUp} ; pen up`);
        penDown = false;
      } else {
        if (!penDown) {
          lines.push(`M280 P0 S${servoPenDown} ; pen down`);
          penDown = true;
        }
        lines.push(`G1 X${x} Y${y} F${maxFeedrate}`);
      }
    }

    if (penDown) {
      lines.push(`M280 P0 S${servoPenUp} ; pen up`);
    }
  }

  lines.push('G0 X0 Y0 ; return home');
  return lines;
}
